CREATE TABLE Student(id INT,LEVEL INT,term INT,NAME VARCHAR(20))
ALTER TABLE Student CHANGE COLUMN id id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
INSERT INTO Student(LEVEL,term,NAME)VALUES(3,2,'karim'),(2,1,'rahim'),(4,2,'Abdur'),(1,2,'rahman')

CREATE TABLE Grade(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,gpa FLOAT NOT NULL,s_id INT,
FOREIGN KEY fk_grade_sid(s_id) REFERENCES Student(id))
INSERT INTO Grade(gpa,s_id)VALUES(3.75,3),(4,2),(2.34,4),(3.48,1)

UPDATE grade SET gpa=4 WHERE s_id=1

DELETE FROM grade WHERE s_id=1

DELETE FROM Student WHERE id=4