CREATE DATABASE practice
CREATE TABLE leap_year(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,YEAR INT)
INSERT INTO leap_year(YEAR) VALUES(2001),(2010),(2000),(2100),(2024),(1500),(2300)
UPDATE leap_year SET YEAR=1500 WHERE id=6

DELIMITER $$
CREATE FUNCTION grade(YEAR INT)
RETURNS VARCHAR(50)
DETERMINISTIC
BEGIN

IF YEAR%400=0 THEN RETURN'Leap year';

ELSEIF YEAR%100=0 THEN RETURN'Not leap year';

ELSEIF YEAR%4=0 THEN RETURN'Leap year';

ELSE RETURN'Not leap year';

END IF;
END $$
DELIMITER ;
DROP FUNCTION grade

SELECT id,grade(YEAR) AS YEAR FROM leap_year
